---
title: "exploring the simulation data"
output: html_notebook
---

lets explore the simulation data I have as of 5-9-2017. Which should be all of the simulations with 1000 Codons, and 3 alpha and omega rate categories

```{r load_dat}
library(dplyr)
library(stringr)
library(readr)
dat <- read_csv("final_results/All_5_25_17_processed.csv") #for some reason the TRUTH and results csv are not combining correctly
results <- read_csv("final_results/All_5_25_17_results.csv")
truth <- read_csv("final_results/All_5_25_17_Truth.csv")

```
```{r}
#for right now do this here
add_truth <- function(results, truth){

  n <- truth %>% select(-FILE, -Sites) %>% colnames()
  results[,n]<-NA
  for( i in seq(from = 1, to = nrow(truth), by = 1)){
    temp = which(str_detect(results$FILE,truth$FILE[i]))
    results[temp,n]<-truth[i,3:length(truth)]
  }
  return(results)
}

dat = add_truth(results,truth)
```


```{r}
#look at data

dat %>% group_by( Sites,True.CV,True.omega3.value) %>% count()
```


```{r power_cal_function}
pwr_tab <- function(dat) {
  
  
  A1.dat = dat
  A1.basic = A1.dat %>% group_by(True.omega3.value, True.CV) %>% summarise(num_reps = n())
  
  A1.BUSTED = A1.dat %>% group_by(True.omega3.value,True.CV ) %>% filter(BUSTED.P <
                                                                               0.05) %>% tally()
  A1.BUSTED = rename(A1.BUSTED, "BUSTED_PWR" = n)
  
  A1.SRV = A1.dat %>%  group_by(True.omega3.value, True.CV) %>% filter(BUSTED.SRV.P <
                                                                              0.05) %>%  tally()
  A1.SRV = rename(A1.SRV, "SRV_PWR" = n)
  
  A1.pwr.tab = full_join(A1.BUSTED, A1.SRV, by = c("True.omega3.value", "True.CV")) %>% 
    full_join(., A1.basic, by = c("True.omega3.value", "True.CV"))
  
  
  
  A1.means = A1.dat %>% group_by(True.omega3.value) %>%   summarise(
    "$BUSTED \\omega_3$ MLE" = mean(BUSTED.omega3.MLE),
    "SRV $\\omega_3$ MLE" = mean(BUSTED.SRV.omega3.MLE),
    "Mean CV" = mean(CV.SRV)
  )
  A1.pwr.tab = full_join(A1.pwr.tab, A1.means, by = "True.omega3.value")
  A1.pwr.tab = replace(A1.pwr.tab, is.na(A1.pwr.tab), 0)
  A1.pwr.tab$BUSTED_PWR = A1.pwr.tab$BUSTED_PWR / A1.pwr.tab$num_reps
  A1.pwr.tab$SRV_PWR = A1.pwr.tab$SRV_PWR / A1.pwr.tab$num_reps
  return(A1.pwr.tab)
}
```

```{r exploration}
library(ggplot2)
library(reshape2)

dat %>% group_by(True.CV,True.omega3.value) %>% count()
```

```{r}
power_cal= pwr_tab(dat)
power_cal %>% select(one_of(c(
  "True.omega3.value", "True.CV", "BUSTED_PWR", "SRV_PWR"
  ))) %>% melt(id.vars = c("True.omega3.value", "True.CV")) %>% ggplot(aes(
  x = True.omega3.value,
  y = value,
  color = interaction(True.CV, variable, sep = " ")
  )) +
  geom_point() + geom_smooth() + labs(x = expression("True " * omega[3]),
  y = "Power",
  color = "CV and Analysis") 

temp=   power_cal %>% select(one_of(
  c("True.omega3.value", "True.CV", "BUSTED_PWR", "SRV_PWR")
)) %>% melt(id.vars = c("True.omega3.value", "True.CV"))
 temp%>% ggplot(aes(x=True.omega3.value, y = True.CV))+ geom_raster(aes(fill = value))+ facet_grid(~variable)+
  labs(x =expression("True "*omega[3]), y = "True CV of SRV", color = "Power")

```

